### PR TITLE
Update to go-1.19, linter fixes

### PR DESCRIPTION
**Pull request by majst01**

### CODE REVIEW

**Comment by mwennrich** [comment]
```
$ k logs -n latest csi-lvm-controller-latest-58c7d676ff-sk6lv
I0908 09:49:47.353653       1 main.go:161] Provisioner started
F0908 09:49:47.353701       1 controller.go:878] Error creating lock: endpoints lock is removed, migrate to endpointsleases
```
we will probably have to wait for a new sig-storage-lib-external-provisioner release: https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/123

**Comment by majst01** [comment]
> ```
> $ k logs -n latest csi-lvm-controller-latest-58c7d676ff-sk6lv
> I0908 09:49:47.353653       1 main.go:161] Provisioner started
> F0908 09:49:47.353701       1 controller.go:878] Error creating lock: endpoints lock is removed, migrate to endpointsleases
> ```
> 
> we will probably have to wait for a new sig-storage-lib-external-provisioner release: [kubernetes-sigs/sig-storage-lib-external-provisioner#123](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/123)

Didnt change anything there ?

**Comment by mwennrich** [comment]
> > ```
> > $ k logs -n latest csi-lvm-controller-latest-58c7d676ff-sk6lv
> > I0908 09:49:47.353653       1 main.go:161] Provisioner started
> > F0908 09:49:47.353701       1 controller.go:878] Error creating lock: endpoints lock is removed, migrate to endpointsleases
> > ```
> > we will probably have to wait for a new sig-storage-lib-external-provisioner release: [kubernetes-sigs/sig-storage-lib-external-provisioner#123](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/123)
> 
> Didnt change anything there ?

Probably the client-go go.mod update: https://github.com/kubernetes/client-go/commit/276ea3ed979947d7cdd4b3d708862245ddcd8883

**Comment by majst01** [comment]
> > > ```
> > > $ k logs -n latest csi-lvm-controller-latest-58c7d676ff-sk6lv
> > > I0908 09:49:47.353653       1 main.go:161] Provisioner started
> > > F0908 09:49:47.353701       1 controller.go:878] Error creating lock: endpoints lock is removed, migrate to endpointsleases
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > we will probably have to wait for a new sig-storage-lib-external-provisioner release: [kubernetes-sigs/sig-storage-lib-external-provisioner#123](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/123)
> > 
> > 
> > Didnt change anything there ?
> 
> Probably the client-go go.mod update: [kubernetes/client-go@276ea3e](https://github.com/kubernetes/client-go/commit/276ea3ed979947d7cdd4b3d708862245ddcd8883)

OK will revert

**Comment by mwennrich** [comment]
```
ok 3 deploy csi-lvm-controller
ok 4 csi-lvm-controller running
ok 5 create pvc
ok 6 deploy linear pod
ok 7 deploy block pod
ok 8 linear pvc bound
ok 9 linear pod running
ok 10 block pvc bound
ok 11 block pod running
ok 12 delete linear pod
ok 13 delete block pod
ok 14 simulate reboot
ok 15 deploy linear pod again
ok 16 deploy block pod again
ok 17 linear pod stays pending
ok 18 block pod stays pending
ok 19 start reviver
ok 20 linear pod running again
ok 21 block pod running again
ok 22 final delete linear pod
ok 23 final delete block pod
ok 24 delete pvc
ok 25 clean up
```
local minikube-test is ok now
metalci-job needs https://github.com/metal-stack/csi-lvm/pull/57/commits/44f1d6fe888c027989ce85a2642c25724a60309a

**Review by mwennrich — APPROVED** [review]

**Pull request merged**
